name: Chezmoi Validation

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Install chezmoi (Linux/Mac)
        if: runner.os != 'Windows'
        run: sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
      - name: Install chezmoi (Windows)
        if: runner.os == 'Windows'
        shell: pwsh
        run: choco install chezmoi -y
      - name: Initialize dotfiles
        shell: bash
        run: chezmoi init --source "$GITHUB_WORKSPACE" --branch "$GITHUB_REF_NAME"
      - name: Validate
        shell: bash
        run: chezmoi doctor
